### PR TITLE
Inventory patch

### PR DESCRIPTION
**Pull request by daRoof**
Added packed volume for stock inventory for KSP 1.11

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
How did you determine the volume?

**Comment by daRoof** [comment]
I set it to a third of the volume of the stock magnetometer.
Comparing the sizes, it seems about right. Maybe even a little too high.

**Comment by daRoof** [comment]
Do you have a better idea how to determine the volume?

**Comment by linuxgurugamer** [comment]
Actually, yes.  I have a new mod, KSP_PartVolumes, which calculates it on the fly.  For now, I'm relying on that for updating my mods, but eventually I'll be taking the data and merging it with the mods.

Thanks for the PR, it's just a coincidence that I had this new mod just after you posted.

**Pull request closed without merging**
